In [ ]:
class Exp:
    def eval(self):
        return eval(str(self))
    
class BinExp(Exp):
    def __init__(self, left, operator, right):
        self.operator = operator
        self.left = left
        self.right = right
        
    def __str__(self):
        return str(self.left) + " " + self.operator + " " + str(self.right)
        
class UnExp(Exp):
    def __init__(self, operator, right):
        self.operator = operator
        self.right = right
        
        
class IntLit(Exp):
    def __init__(self, num):
        self.num = num

    # @override
    def __str__(self):
        return str(self.num)

class FloatLit(Exp):
    def __init__(self, num):
        self.num = num

    # @override
    def __str__(self):
        return str(self.num)
        


x = BinExp('+',IntLit(3),BinExp('*',IntLit(4),FloatLit(2.0)))

In [ ]:
print(BinExp('*','4','2.0').eval())

8.0


In [ ]:
class Exp:
    def eval(self):
        return eval(str(self))

    # def printPrefix(self):
    #     print(self.printPrefix())


class IntLit(Exp):
    def __init__(self, num):
        self.num = num

    # @override
    def __str__(self):
        return str(self.num)

class FloatLit(Exp):
    def __init__(self, num):
        self.num = num

    # @override
    def __str__(self):
        return str(self.num)

class UnExp(Exp):
    def __init__(self, operator, operand):
        self.operator = operator
        self.operand = operand
    
    def __str__(self):
        return self.operator + str(self.operand)

class BinExp(Exp):
    def __init__(self, left,operator, right):
        self.operator = operator
        self.left = left
        self.right = right

    def __str__(self):
        return str(self.left) + " " + self.operator + " " + str(self.right)


if __name__ == '__main__':
    # t = BinExp(IntLit(3),'*', BinExp(2,'+', FloatLit(0.2)))
    # print(t)
    # t.eval()

    x = BinExp(IntLit(3), '+', BinExp(IntLit(4), '*', FloatLit(2.0)))
    print(x)
    print(x.eval())

3 + 4 * 2.0
11.0


In [ ]:
#bai 2
class Exp:
    def eval(self):
        return eval(str(self))

    def printPrefix(self):
        print(str(self.printPrefix()))

    def __str__(self):
        return str(self.exp)
    
class BinExp(Exp):
    def __init__(self, left, operator, right):
        self.operator = operator
        self.left = left
        self.right = right
        
    def __str__(self):
        return str(self.left) + " " + self.operator + " " + str(self.right)
      
    

    def printPrefix(self):
        return str(self.operator) + " " + self.left.printPrefix()+self.right.printPrefix()

        
class UnExp(Exp):
    def __init__(self, operator, right):
        self.operator = operator
        self.right = right
        
    def __str__(self):
        return self.operator + " " + str(self.right)

    def printPrefix(self):
        return str(self.operator) + ". " + self.right.printPrefix()

        
class IntLit(Exp):
    def __init__(self, num):
        self.num = num

    def __str__(self):
        return str(self.num)+" "

    def printPrefix(self):
        return str(self.num)+" "

class FloatLit(Exp):
    def __init__(self, num):
        self.num = num

    def __str__(self):
        return str(self.num)
    
    def printPrefix(self):
        return str(self.num)

x = BinExp(UnExp("-", IntLit(4)), "+", BinExp(IntLit(3), "*", FloatLit(2.0)))
print(x)
print(x.printPrefix())

- 4  + 3  * 2.0
+ -. 4 * 3 2.0


In [ ]:
class Exp:
    # def __init__(self, string):
    #     self.exp = string
    def eval(self):
        return eval(str(self))

    def printPrefix(self):
        print(str(self.printPrefix()))

    def __str__(self):
        return str(self.exp)


class BinExp(Exp):
    def __init__(self, left, op, right):
        self.op = op
        self.left = left
        self.right = right

    def printPrefix(self):
        return str(self.op) + " " + self.left.printPrefix()+self.right.printPrefix()

    def __str__(self):
        return str(self.left) + str(self.op) + str(self.right)


class UnExp(Exp):
    def __init__(self, op, right):
        self.op = op
        self.right = right

    def __str__(self):
        return str(self.op)+str(self.right)

    def printPrefix(self):
        return str(self.op)+". "+self.right.printPrefix()


class IntLit(Exp):
    def __init__(self, number):
        self.value = number

    def __str__(self):
        return str(self.value)+" "

    def printPrefix(self):
        return str(self.value)+" "


class FloatLit(Exp):
    def __init__(self, number):
        self.value = float(number)

    def __str__(self):
        return str(self.value)

    def printPrefix(self):
        return str(self.value)


y = BinExp(UnExp("-", IntLit(4)), "+", BinExp(IntLit(3), "*", FloatLit(2.0)))


print(y.printPrefix())
print(y)
# print(y.eval())

+ -. 4 * 3 2.0
-4 +3 *2.0


In [ ]:
class Exp:
    def eval(self):
        return eval(str(self))

    def printPrefix(self):
        print(str(self.printPrefix()))

    def __str__(self):
        return str(self.exp)
    
class Eval:
    pass
    
class PrintPrefix:
    pass
    
class PrintPostfix:
    pass

class BinExp(Exp):
    def __init__(self, left, operator, right):
        self.operator = operator
        self.left = left
        self.right = right
        
    def __str__(self):
        return str(self.left) + " " + self.operator + " " + str(self.right)
      
    

    def printPrefix(self):
        return str(self.operator) + " " + self.left.printPrefix()+self.right.printPrefix()

        
class UnExp(Exp):
    def __init__(self, operator, right):
        self.operator = operator
        self.right = right
        
    def __str__(self):
        return self.operator + " " + str(self.right)

    def printPrefix(self):
        return str(self.operator) + ". " + self.right.printPrefix()

        
class IntLit(Exp):
    def __init__(self, num):
        self.num = num

    def __str__(self):
        return str(self.num)+" "

    def printPrefix(self):
        return str(self.num)+" "

class FloatLit(Exp):
    def __init__(self, num):
        self.num = num

    def __str__(self):
        return str(self.num)
    
    def printPrefix(self):
        return str(self.num)

In [ ]:
import numpy as np
arr = np.zeros((10,10))
print(arr)
arr[:,0] = 1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import math
import os
import random
import re
import sys
from sklearn import datasets, linear_model
import numpy as np 

# Complete the twoPluses function below.
def Linear_Regression(grid):
    grid = np.array(grid)
    y = grid[:,-1]
    y = np.array([y]).T
    X = grid[:,:-1]
    # Building Xbar 
    one = np.ones((X.shape[0], 1))
    Xbar = np.concatenate((one, X), axis = 1)
    regr = linear_model.LinearRegression(fit_intercept=False) # fit_intercept = False for calculating the bias
    regr.fit(Xbar, y)
    return regr.coef_[0]
    
    
def cal(predict, feature_house):
    res = 0
    print(feature_house)
    for i in range(len(feature_house)):
        res += predict[(i+1)] * feature_house[i]
    return res + predict[0]

if __name__ == '__main__':
    # fptr = open(os.environ['OUTPUT_PATH'], 'w')

    

    f = 2

    n = 7

    grid = [[0.18, 0.89, 109.85],
[1.0, 0.26, 155.72],
[0.92, 0.11, 137.66],
[0.07, 0.37, 76.17],
[0.85, 0.16, 139.75],
[0.99, 0.41, 162.6],
[0.87, 0.47, 151.77]]

    

    predict = Linear_Regression(grid)
    print(predict)

    n = 4
    house = [[0.49, 0.18],
             [0.57, 0.83],
             [0.56, 0.64],
             [0.76, 0.18]]
    for i in range(n):
        feature_house = [float(x) for x in house[i]]
        res_item = cal(predict, feature_house)
        print(res_item)
    # fptr.close()

[52.41149905 90.69331739 46.46296549]
[0.49, 0.18]
105.2145583510694
[0.57, 0.83]
142.6709513072992
[0.56, 0.64]
132.9360546912469
[0.76, 0.18]
129.7017540450245


In [ ]:
string = 'abcb'
print(string.count('b'))
char = 'b'
print(char == string[1])

2
True


In [ ]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
zip = [[a[i], b[i]] for i in range(len(a))]
print(zip)

[[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]]


In [ ]:
def primeCount(n):
    prime_lst = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]
    arr = [2] + [0]*15
    for i in range(1,16):
      arr[i] = arr[i-1]*prime_lst[i]
    res = 0
    for prime in arr:
        if n > prime:
            res += 1
        else:
            return res
print(primeCount(5000))

5


In [ ]:
lst = [1,3,4,5]
def subsum(lst):
  if len(lst) == 0:
    return []
  if len(lst) == 1:
    return [lst[0]]
  return subsum(lst[:-1]) + [subsum(lst[:-1])[-1] + lst[-1]]
print(subsum([1]))

[1]


In [ ]:
lst = [1,3,4,5]
from functools import reduce
def subsum(lst):
  if len(lst) == 0:
    return []
  return reduce(lambda x,y: x + [x[-1]+y],lst[1:],[lst[0]])
print(subsum([1]))


[1]


In [ ]:
b = 3
a = [1,2,3]
Comb = list(map( lambda x: (x,b) , a))
print(Comb)
def HAM(lst,b):
  if len(lst) == 0:
    return []
  return [(lst[0],b)] + HAM(lst[1:],b)
print(HAM(a,b))
type(b)

[(1, 3), (2, 3), (3, 3)]
[(1, 3), (2, 3), (3, 3)]


int

In [ ]:
lst=  [1.5, 2, 'b', 'cd', 3,'abckj',1.5,2,6]
from functools import reduce
def  mul_int( lst):
  lst_int = list(filter(lambda x: isinstance(x, int),lst))
  return reduce(lambda x, y: x*y,lst_int)
print(mul_int( lst))


72


In [ ]:
lst = [2,3.4,5,[1,4.5,[2.2,1],5],6]
def reccount(lst):
  if len(lst) == 0:
    return (0, 0, 0)
  list_lst = reccount(lst[1:])
  if type(lst[0]) is int:
    return (1 + list_lst[0], list_lst[1], list_lst[2]) 
  elif type(lst[0]) is float:
    return (list_lst[0], list_lst[1] + 1, list_lst[2])
  list0_lst = reccount(lst[0])
  return (list_lst[0] + list0_lst[0], list_lst[1] + list0_lst[1], list_lst[2] + 1 + list0_lst[2])


def hicount(lst):#use filter
  list_list = list(filter(lambda x: type(x) is list, lst))
  count_lst = len(list_list)
  count_int = len(list(filter(lambda x: type(x) is int, lst)))
  count_float = len(list(filter(lambda x: type(x) is float, lst)))
  if count_lst == 0:
    return (count_int, count_float, 0)
  rec_res = hicount(list_list[0])
  return (count_int + rec_res[0], count_float + rec_res[1], count_lst + rec_res[2])

# lst = [2,3.4,5,[1,4.5,[2.2,1],5],6]
from functools import reduce
def hicount1(lst):#use reduce
  def inner(y):
    if type(y) is int:
      return (1,0,0)
    elif type(y) is float:
      return (0,1,0)
    return (hicount1(y)[0], hicount1(y)[1], hicount1(y)[2] + 1)
  return reduce(lambda x, y: (x[0] + inner(y)[0], x[1] + inner(y)[1], x[2] + inner(y)[2]),lst,(0,0,0))

print(reccount(lst))
print(hicount(lst))
print(hicount1(lst))


(6, 3, 2)
(6, 3, 2)
(6, 3, 2)


In [ ]:
a = (1,2,3)
print(type(a) is tuple)
print(a[0])

True
1


In [ ]:
from functools import reduce
def hicount1(lst):#use reduce
  def inner(y):
    if type(y) is int:
      return (1,0,0)
    elif type(y) is float:
      return (0,1,0)
    return (hicount1(y)[0], hicount1(y)[1], hicount1(y)[2] + 1)
  return reduce(lambda x, y: (x[0] + inner(y)[0], x[1] + inner(y)[1], x[2] + inner(y)[2]),lst,(0,0,0))


lst = [2,3.4,5,[1,4.5,[2.2,1],5],6]
print(hicount1(lst))

(6, 3, 2)


In [2]:
import numpy as np
a = ([1,2,3], [1,4,5], [6,7,8])
a = np.array(a)
print(a)
print(a[1,1])
dtype = [('id', int), ('profit', float), ('x', int), ('y', int)]
values = [(i, 0, 4, 5) for i in range(3)]
current_profit = np.array(values, dtype=dtype)
print(current_profit)
print(current_profit[0][-1])
b = (1,2,3,4)
print(b[1:])

[[1 2 3]
 [1 4 5]
 [6 7 8]]
4
[(0, 0., 4, 5) (1, 0., 4, 5) (2, 0., 4, 5)]
5
(2, 3, 4)
